### ISSUE TITLE
Indiegogo\Test\ is in autoload instead of autoload-dev

### ISSUE THREAD

**Issue by 7ochem** [tiamo/indiegogo#1]
When looking at the `composer.json` I'm seeing a minor inconsistency:

      "require": {
        "php": ">=5.4.0"
      },
      "require-dev": {
        "phpunit/phpunit": "~4.4"
      },
      "autoload": {
        "psr-4": {
          "Indiegogo\\": "src/",
          "Indiegogo\\Tests\\": "tests/"
        }
      }

PhpUnit is in the require-dev section, however the Indiegogo\Tests\ autoload is in the regular autoload section instead of the autoload-dev section. Can this be moved there?

**Comment by tiamo** [comment]
Yep, thanks!
